[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moondev"
version = "0.1.0"
authors = [
    { name="Moon Dev", email="moondev@example.com" },
]
description = "Moon Dev's AI Agents for Trading"
requires-python = ">=3.8"
